name: ci

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPO: ${{ vars.TF_VAR_ECR_REPO_NAME }}

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.TF_GITHUB_ROLE_ARN }}
          aws-region: ${{ vars.TF_VAR_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug (safe)
        run: |
          echo "AWS_REGION=$AWS_REGION"
          echo "ECR_REPO=$ECR_REPO"

      - name: Build image
        run: |
          test -n "$ECR_REPO"
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE_URI_SHA="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$GITHUB_SHA"
          IMAGE_URI_LATEST="$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest"
          docker build -t "$IMAGE_URI_SHA" -t "$IMAGE_URI_LATEST" ./app
          echo "IMAGE_URI=$IMAGE_URI_SHA" >> "$GITHUB_ENV"
          echo "IMAGE_URI_LATEST=$IMAGE_URI_LATEST" >> "$GITHUB_ENV"

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ env.IMAGE_URI }}
          severity: "HIGH,CRITICAL"
          exit-code: "1"
          format: "table"
          trivyignores: .trivyignore
          ignore-unfixed: "true"

      - name: Push image
        run: |
          docker push "$IMAGE_URI"
          docker push "$IMAGE_URI_LATEST"

      - name: Output image uri
        run: |
          echo "image_uri=$IMAGE_URI" >> "$GITHUB_OUTPUT"
        id: image
